# Generated by Django 5.0.6 on 2024-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('origem', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
            ],
        ),
    ]
