# Generated by Django 5.0.6 on 2024-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='movimentacao',
            field=models.CharField(default='', max_length=20),
        ),
    ]
